<a href="https://colab.research.google.com/github/BoyaShivatejaNaidu/ML-NLP/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
#Problem 1
import numpy as np
output_lines = [] #create output file

#Generate 2D NumPy array
array = np.random.randint(1, 51, size=(5, 4))
output_lines.append("1. Original Array:\n" + str(array))

#Anti-diagonal extraction
anti_diagonal = [int(array[i, -1 - i]) for i in range(min(array.shape))]
output_lines.append("\nAnti-diagonal Elements:\n" + str(anti_diagonal))

#Row-wise max
row_max = np.max(array, axis=1).tolist()
output_lines.append("\nMaximum Value in Each Row:\n" + str(row_max))

#Elements<=mean
mean_val = np.mean(array)
filtered_elements = array[array <= mean_val].tolist()
output_lines.append(f"\nOverall Mean = {mean_val:.2f}")
output_lines.append("Filtered Elements (≤ Mean):\n" + str(filtered_elements))

#Boundary traversal
def numpy_boundary_traversal(matrix):
    rows, cols = matrix.shape
    if rows == 1:
        return matrix[0].tolist()
    elif cols == 1:
        return matrix[:, 0].tolist()

    boundary = []
    boundary.extend(matrix[0, :])                     # top row
    boundary.extend(matrix[1:-1, -1])                 # right column
    boundary.extend(matrix[-1, ::-1])                 # bottom row reversed
    boundary.extend(matrix[-2:0:-1, 0])               # left column reversed
    return [int(x) for x in boundary]

boundary = numpy_boundary_traversal(array)
output_lines.append("\nBoundary Traversal (Clockwise):\n" + str(boundary))

#Save to file & print to console
with open("problem1_output.txt", "w") as f:
    f.write("\n".join(output_lines))
for line in output_lines:
    print(line)


1. Original Array:
[[35 13 47 27]
 [15 38 28 50]
 [ 5 35  4 50]
 [47 30 45 34]
 [27 19 41  3]]

Anti-diagonal Elements:
[27, 28, 35, 47]

Maximum Value in Each Row:
[47, 50, 50, 47, 41]

Overall Mean = 29.65
Filtered Elements (≤ Mean):
[13, 27, 15, 28, 5, 4, 27, 19, 3]

Boundary Traversal (Clockwise):
[35, 13, 47, 27, 50, 50, 34, 3, 41, 19, 27, 47, 5, 15]


In [61]:
#Problem 2
import numpy as np
output_lines = []

#Generate 1D NumPy array of 20 random floats between 0 and 10
array = np.random.uniform(0, 10, 20)
array_rounded = np.round(array, 2)
output_lines.append("2. Original Array (full precision):\n" + str(array.tolist()))
output_lines.append("Rounded Array (2 decimal places):\n" + str(array_rounded.tolist()))

#Calculate min, max, median
min_val = np.min(array_rounded)
max_val = np.max(array_rounded)
median_val = np.median(array_rounded)
output_lines.append(f"\nMinimum: {min_val}")
output_lines.append(f"Maximum: {max_val}")
output_lines.append(f"Median: {median_val}")

#Replace all elements < 5 with their squares
modified_array = np.where(array_rounded < 5, np.round(array_rounded**2, 2), array_rounded)
output_lines.append("\nModified Array (elements < 5 squared):\n" + str(modified_array.tolist()))

#Function to sort in alternating smallest-largest pattern
def numpy_alternate_sort(arr):
    sorted_arr = np.sort(arr)
    result = []
    i, j = 0, len(sorted_arr) - 1
    while i <= j:
        result.append(sorted_arr[i])
        if i != j:
            result.append(sorted_arr[j])
        i += 1
        j -= 1
    return np.round(result, 2)

alternating_sorted = numpy_alternate_sort(array_rounded)
output_lines.append("\nAlternating Sorted Array (min, max, 2nd min, 2nd max...):\n" + str(alternating_sorted.tolist()))

#Save to file & Print to console
with open("problem2_output.txt", "w") as f:
    f.write("\n".join(output_lines))
for line in output_lines:
    print(line)


2. Original Array (full precision):
[9.322481816134106, 8.107120333448453, 8.832550042895564, 5.33801415001308, 4.442554734639284, 9.195979047951363, 6.596631907607241, 7.296711325304132, 8.467411254618609, 4.794619811422253, 6.101609079163177, 4.185727447927929, 1.2980081428878387, 6.337771194135577, 3.139188498060336, 9.339043699114477, 8.341768367094751, 2.3348279271764962, 5.3999149327017735, 8.002516264698082]
Rounded Array (2 decimal places):
[9.32, 8.11, 8.83, 5.34, 4.44, 9.2, 6.6, 7.3, 8.47, 4.79, 6.1, 4.19, 1.3, 6.34, 3.14, 9.34, 8.34, 2.33, 5.4, 8.0]

Minimum: 1.3
Maximum: 9.34
Median: 6.47

Modified Array (elements < 5 squared):
[9.32, 8.11, 8.83, 5.34, 19.71, 9.2, 6.6, 7.3, 8.47, 22.94, 6.1, 17.56, 1.69, 6.34, 9.86, 9.34, 8.34, 5.43, 5.4, 8.0]

Alternating Sorted Array (min, max, 2nd min, 2nd max...):
[1.3, 9.34, 2.33, 9.32, 3.14, 9.2, 4.19, 8.83, 4.44, 8.47, 4.79, 8.34, 5.34, 8.11, 5.4, 8.0, 6.1, 7.3, 6.34, 6.6]


In [62]:
#Problem 3
import pandas as pd
import numpy as np

#Output container
output_lines = []

#Names and subjects
names = ['Shiva', 'Sarthak', 'Deva', 'Abhiram', 'Lakshmi', 'Neena', 'Sriya', 'Shalini', 'Shambhavi', 'Shikha']
subjects = ['Electronics', 'Anatomy', 'Physiology', 'Biochemistry', 'Biomechanics',
            'Math', 'Physics', 'Socialscience', 'PE', 'Finance']

#Random scores between 50 and 100
scores = np.random.randint(50, 101, size=10)

#Create DataFrame
df = pd.DataFrame({
    'Name': names,
    'Subject': subjects,
    'Score': scores,
    'Grade': ''
})

#Function to assign grade based on score
def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

#Assign grades
df['Grade'] = df['Score'].apply(assign_grade)

output_lines.append("3 .Original Student Data with Grades:\n" + str(df))

#Sort by Score (descending)
sorted_df = df.sort_values(by='Score', ascending=False)
output_lines.append("\nData Sorted by Score (Descending):\n" + str(sorted_df))

#Subject-wise average score
subject_avg = df.groupby('Subject')['Score'].mean().round(2)
output_lines.append("\nAverage Score by Subject:\n" + str(subject_avg))

#Function to filter grades A or B
def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]
passed_df = pandas_filter_pass(df)
output_lines.append("\nStudents with Grade A or B:\n" + str(passed_df))

#Save to file & print
with open("problem3_custom_output.txt", "w") as f:
    f.write("\n\n".join(output_lines))
for line in output_lines:
    print(line, end="\n\n")



3 .Original Student Data with Grades:
        Name        Subject  Score Grade
0      Shiva    Electronics     85     B
1    Sarthak        Anatomy     86     B
2       Deva     Physiology     54     F
3    Abhiram   Biochemistry     57     F
4    Lakshmi   Biomechanics     71     C
5      Neena           Math     92     A
6      Sriya        Physics     75     C
7    Shalini  Socialscience     81     B
8  Shambhavi             PE     94     A
9     Shikha        Finance     97     A


Data Sorted by Score (Descending):
        Name        Subject  Score Grade
9     Shikha        Finance     97     A
8  Shambhavi             PE     94     A
5      Neena           Math     92     A
1    Sarthak        Anatomy     86     B
0      Shiva    Electronics     85     B
7    Shalini  Socialscience     81     B
6      Sriya        Physics     75     C
4    Lakshmi   Biomechanics     71     C
3    Abhiram   Biochemistry     57     F
2       Deva     Physiology     54     F


Average Score by Subj

In [63]:
import pandas as pd
import numpy as np

#Student names and subjects
names = ['Shiva', 'Sarthak', 'Deva', 'Abhi', 'Lakshmi', 'Neena', 'Sriya', 'Shalini', 'Shambhavi', 'Shikha']
subjects = ['Electronics', 'Anatomy', 'Physiology', 'Biochemistry', 'Biomechanics',
            'Math', 'Physics', 'Socialscience', 'PE', 'Finance']

#Generate random marks (50–100) for each student and each subject
marks = {subject: np.random.randint(50, 101, size=len(names)) for subject in subjects}
df = pd.DataFrame(marks)
df.insert(0, 'Name', names)

#Compute total and scaled score (out of 100)
df['Total'] = df[subjects].sum(axis=1)
df['Scaled Score'] = (df['Total'] / (len(subjects) * 100)) * 100

#Assign Grade based on scaled score
def assign_final_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

df['Grade'] = df['Scaled Score'].apply(assign_final_grade)

#Sort by Score descending
sorted_df = df.sort_values(by='Scaled Score', ascending=False)

#Average score for each subject
subject_avg = df[subjects].mean().round(2)

#Function to return students with grade A or B
def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]
passed_df = pandas_filter_pass(df)

#Save all results
#Wide marks table with grades
df_output = df[['Name'] + subjects + ['Total', 'Scaled Score', 'Grade']]
df_output.to_csv("problem3_student_wise_marks.csv", index=False)

#Sorted by score
sorted_df.to_csv("problem3_sorted_by_score.csv", index=False)

#Subject averages
subject_avg.to_csv("problem3_subject_averages.csv")

#A/B grade filter
passed_df.to_csv("problem3_passed_students.csv", index=False)

#print summary
print("3 .Student Data (10 Students × 10 Subjects):\n")
print(df_output.to_string(index=False))

print("\nStudents Sorted by Scaled Score:\n")
print(sorted_df[['Name', 'Scaled Score', 'Grade']].to_string(index=False))

print("\nSubject-wise Average Scores:\n")
print(subject_avg)

print("\nStudents with Grade A or B:\n")
print(passed_df[['Name', 'Scaled Score', 'Grade']].to_string(index=False))


3 .Student Data (10 Students × 10 Subjects):

     Name  Electronics  Anatomy  Physiology  Biochemistry  Biomechanics  Math  Physics  Socialscience  PE  Finance  Total  Scaled Score Grade
    Shiva           88       89          80            91            58    97       59             67  50       65    744          74.4     C
  Sarthak           86       51          97            85            53    64       50             80  72       66    704          70.4     C
     Deva           89       91          76            77            78    67       78             85  87       99    827          82.7     B
     Abhi           67       76          68            84            55    99       84             54  88       93    768          76.8     C
  Lakshmi           94       98          75            82            68    57       71             88  63       57    753          75.3     C
    Neena           70       50          58            85           100    62       89             77 

In [64]:
#Problem 4
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import random

#Output collection
output_lines = []

#Generate synthetic reviews
positive_reviews = ["Definitely one of the funniest movies I have ever seen absolute gold", "really funny movie, really changed my mood", "A fun flick full of laughs.",
                    "Great story and visuals.", "Very funny. Loved every second!"] * 10
negative_reviews = ["I hated this movie.", "Terrible acting and story.", "Waste of time.",
                    "Poorly directed and boring.", "Awful experience."] * 10

reviews = positive_reviews + negative_reviews
sentiments = ['positive'] * 50 + ['negative'] * 50

#Shuffle the dataset
combined = list(zip(reviews, sentiments))
random.shuffle(combined)
reviews, sentiments = zip(*combined)

#Create DataFrame
df = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})

output_lines.append("4. Sample Reviews of 21 JUMP STREET\n" + str(df.head()))

#Tokenize using CountVectorizer
vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']

#Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Train Multinomial Naive Bayes
model = MultinomialNB()
model.fit(X_train, y_train)

#Accuracy on test set
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
output_lines.append(f"\nTest Accuracy: {accuracy:.2f}")

#Prediction function
def predict_review_sentiment(model, vectorizer, review):
    vec = vectorizer.transform([review])
    return model.predict(vec)[0]

#Example usage
example_review = "The film was beautifully shot and well-acted."
predicted_sentiment = predict_review_sentiment(model, vectorizer, example_review)
output_lines.append(f"\nPredicted Sentiment for Example Review:\n\"{example_review}\" \n\nPredicted sentiment\n→{predicted_sentiment}")

#Save to file & print
with open("problem4_output.txt", "w") as f:
    f.write("\n\n".join(output_lines))
for line in output_lines:
    print(line, end="\n\n")


4. Sample Reviews of 21 JUMP STREET
                                              Review Sentiment
0  Definitely one of the funniest movies I have e...  positive
1                                  Awful experience.  negative
2                        A fun flick full of laughs.  positive
3                         Terrible acting and story.  negative
4  Definitely one of the funniest movies I have e...  positive


Test Accuracy: 1.00


Predicted Sentiment for Example Review:
"The film was beautifully shot and well-acted." 

Predicted sentiment
→negative



In [65]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import random

#Create diverse dataset
positive_feedback = [
    "Great product!", "Very useful and well made.", "Loved it, works perfectly.",
    "Excellent build quality.", "Highly recommend.", "This is a top-notch item.",
    "Affordable and high quality.", "Truly worth the money.", "Reliable and impressive.",
    "Amazing design and durability."
] * 10

negative_feedback = [
    "Terrible quality.", "Broke after one use.", "Very disappointed.",
    "Not worth the money.", "Would not recommend.", "Cheap and unreliable.",
    "Completely useless and fragile.", "Awful build and poor service.",
    "Garbage product with bad packaging.", "Extremely dissatisfied."
] * 10

feedback = positive_feedback + negative_feedback
labels = ['good'] * 100 + ['bad'] * 100

#Shuffle dataset
combined = list(zip(feedback, labels))
random.shuffle(combined)
feedback, labels = zip(*combined)

#Create DataFrame
df = pd.DataFrame({'Feedback': feedback, 'Label': labels})
print("5. Sample Feedback Data:\n")
print(df.head(), end="\n\n")

#TfidfVectorizer with better coverage
vectorizer = TfidfVectorizer(max_features=1000, stop_words='english', lowercase=True)
X = vectorizer.fit_transform(df['Feedback'])
y = df['Label']

#Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

#Train Logistic Regression & Evaluate
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

#Prediction Function
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)

#Example Predictions
example_texts = ["Highly recommend this item.", "Completely useless and cheap."]
example_vectors = text_preprocess_vectorize(example_texts, vectorizer)
example_preds = model.predict(example_vectors)

print("\nExample Predictions:\n")
for txt, lbl in zip(example_texts, example_preds):
    print(f"\"{txt}\" → {lbl}")


5. Sample Feedback Data:

                   Feedback Label
0     Cheap and unreliable.   bad
1    Truly worth the money.  good
2      Broke after one use.   bad
3    Truly worth the money.  good
4  Reliable and impressive.  good


Classification Report:

              precision    recall  f1-score   support

         bad       1.00      1.00      1.00        26
        good       1.00      1.00      1.00        24

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50


Example Predictions:

"Highly recommend this item." → good
"Completely useless and cheap." → bad
